language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - TYPO3=6.2.*
  - TYPO3=dev-master

matrix:
  exclude:
    - php: 5.3
      env: TYPO3=dev-master
    - php: 5.4
      env: TYPO3=dev-master


before_script:
  - composer require typo3/cms:$TYPO3
  - composer install --prefer-dist
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=build/logs/clover.xml

after_script:
  - mkdir -p src/FluidTYPO3/Fluidpages
  - ln -s Classes src/FluidTYPO3/Fluidpages
  - vendor/bin/coveralls
